### ISSUE TITLE
Moar threads

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1255]
Since #709 has been in beta few people have enabled it. Let's put a little more effort into it, enable it by default and see what the reaction is. Some thoughts below:

### Fixing what is there
- [x] make sure the order is by datetime https://github.com/octobox/octobox/pull/1270
- [x] clean up the UI and separate the thread window
- [x] fix responsive breakpoints so that it doesn't swap between responsive and table view notifications
- [x] ensure that threads are marked as read on GH #1277 
- [ ] ~collapse initial comment if read~
- [x] clean up the expand action (inc. scrolling the page if at the bottom.
- [ ] ~Make the 'view on GH' external link more obvious~
- [ ] Update url when closing a thread #1475 
- [ ] Update status of threads when receiving a webhook #1476 

### Extending what is there
* [ ] add comment count on notifications list #1247
* [ ] Scroll to the last unread notification when clicking a thread
* ~Highlight current thread viewed in notifications table~
* [ ] ~Paginate long threads~
* [ ] Adding/mapping keyboard controls for threads
* ~Add reactions to comments~
* [ ] Add response UI

**Comment by BenJam** [comment]
For anyone reading this who is thinking 'what is he on about?' go to settings and select 'on octobox' from the 'view threads' menu.

**Comment by andrew** [comment]
I believe that commenting and reacting will require changing the permissions of the GitHub app to "Issue write" and "Pull Request write"

**Comment by andrew** [comment]
Visually, how about properly dividing the columns by a border from top to bottom? It looks a bit weird when you only have a small number of notifications in your inbox:

<img width="912" alt="screen shot 2018-11-19 at 11 43 13" src="https://user-images.githubusercontent.com/1060/48705226-83294b00-ebf0-11e8-8e9a-ec1e257333b4.png">

**Comment by BenJam** [comment]
@andrew that footer is really irritating anyway. I wonder whether it should be pushed to the bottom of the whole page which I would prefer to having at the bottom of the window.

**Comment by andrew** [comment]
I’d prefer to move it completely out of the way, perhaps in an “about” item in the drop down top right?
